### ISSUE TITLE
When i try to upload the contract into LocalTerra using Station, i am getting : Wasm contract doesn't have required export: "interface_version_6"

### ISSUE THREAD

**Issue by ssenathi** [terra-money/cosmwasm-contracts#2]
When i try to upload the contract into LocalTerra using Station, i get following error.

rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract doesn't have required export: "interface_version_6". Exports required by VM: ["interface_version_6", "instantiate", "allocate", "deallocate"]. Contract version too old for this VM?: store wasm con
![image](https://user-images.githubusercontent.com/851348/127157856-56d482ca-db16-47fd-a29d-4260cc01807e.png)
tract failed: invalid request

**Comment by hanjukim** [comment]
Sorry, please use `git clone --branch v0.4.1 --depth 1 https://github.com/terra-money/localterra` for columbus-4 contract development
